module.exports = {
    'master chief': [
        'no thanks to your driving, yes',
        'Enough! The Flood is spreading. If we activate Halo\'s defenses, we can wipe them out.',
        'Sir. Permission to leave the station... To give the Covenant back their bomb.',
        'This thing is right. Halo is a weapon. Your Prophets are making a big mistake.',
        'That Brute has the Index. And Miranda and Johnson. He can activate the ring.',
        'Sir, finishing this fight.',
        'On Halo, you tried to kill Cortana. You tried to kill me.',
        'Thought I\'d try shooting my way out. mix things up a little.',
        'You know me. When I make a promise...',
        'Wake me… When you need me.',
        'Yes sir, I need a weapon.',
        'We\'ll head for the Portal. And we\'ll all go home.',
        'Does he usually mention me?'
    ],
    'arbiter': [
        'what would you have your arbiter do?',
        'tartarus, the prophets have betrayed us',
        'were it so easy',
        'quickly. let us find their ship. make short work of this abomination',
        'the prophet will die by my hands, not theirs',
        'this is our fight, and i will see it finished',
        'parasite. rise up and i shall kill you.  again and again',
        'by the time I learned of the demon\'s intent, there was nothing i could do',
        'if they came to hear me beg, they will be disappointed',
        'at the center of this zone, is a sacred icon critical to the great journey. i must find it',
        'kill me or release me, parasite. but do not waste my time with talk',
        'your ignorance already destroyed one of the sacred rings demon, it shall not destroy another',
        'there are things about halo that even the hierarchs do not understand',
        'And so... you must be silenced!'
    ],
    'cortana' : [
        'i think we both know the answer to that',
        'The enemy has captured Captain Keyes, and are holding him aboard one of their cruisers, the Truth and Reconciliation.',
        'I thought the Covenant had eliminated all the Marine forces in this area.',
        'I\'ve spent the last 12 hours cooped up in here, watching you toady about, helping that thing get set to slit our throats!',
        'Do what? I have the Index! You can just float and sputter!',
        'We did what we had to do! For Earth! An entire Covenant armada obliterated, and the Flood! We had no choice. Halo ... It\'s finished.',
        'If this thing blows up, I\'m never talking to you again!',
        'Just one question: What if you miss?',
        'Find a hole, stay put. We\'ll come to you.',
        'Thanks for the tank. He never gets me anything.',
        'Hang on to your helmet!',
        'Don\'t make a girl a promise... If you know you can\'t keep it...',
        'They let me pick, did I ever tell you that? Choose whichever Spartan I wanted.',
        'I\'m a thief... but I keep what I steal.',
        'Just keep your head down... There\'s two of us in here now, remember.',
        'Wait, you two made nice?! What else have you been up to...?',
        'Halo. It\'s so new, unfinished. I\'m not exactly sure what will happen when we fire it.',
        'If we don\'t make it... It\'s been an honor serving with you, John.',
        'Keep your head down! There\'s two of us in here now, remember?'
    ],
    'prophet of truth': [
        'soon the great journey will begin, but when it does, the weight of your heresy will stay your feet, and you shall be left behind',
        'You were right to focus your attention on the Flood. But this Demon, this Master Chief...',
        'You are one of our most treasured instruments. Long have you led your fleet with honor and distinction. But your inability to safeguard Halo... was a colossal failure.',
        'The Council decided to have you hung by your entrails and your corpse paraded through the city. But, ultimately, the terms of your execution are up to me',
        'Halo\'s destruction was your error and you rightly bear the blame. But the Council was... overzealous. We know you are no heretic.',
        'This heretic, and those who follow him, must be silenced.',
        'Your haste has jeopardized the fulfillment of our Covenant and threatened our grand design.',
        'How to start this process? For ages, we searched for one who might unlock the secrets of the ring. An Oracle. And with your help, we found it.',
        'You will journey to the surface of the ring, and retrieve this Sacred Icon. With it, we shall fulfill our promise.',
        'There are those who said this day would never come. What are they to say now?',
        'The release of the parasite was unexpected, unfortunate. But, there is no need to panic.',
        'The parasite did not defeat the Forerunners... and it shall not defeat us.',
        'If you will falter, know this... one final effort is all that remains.',
        'Stop, you imbecile! He wants you to kill him.',
        'Can you see, Arbiter? The moment of salvation is at hand.',
        'Re-commissioning the guard was a radical step, but recent events have made it abundantly clear that the Elites can no longer guarantee our safety.',
        'You are, all of you, vermin. Cowering in the dirt, thinking... what, I wonder? That you might escape the coming fire? No. Your world will burn until its surface is but glass!'
    ],
    'sargent johnson': [
        'all you greenhorns who wanted to see the covenant up close... today is your lucky day',
        'goddamnit jenkins, fire your weapon',
        'this is it baby.  Hold me.',
        'get up, so i can kill you again',
        'and you told me you were gonna wear something nice',
        'for a brick, he flew pretty good',
        'dear humanity... we regret being alien bastards. we regret coming to earth. and we most definitely regret that the corps just blew up our raggedy-ass fleet',
        'oh, i know what the ladies like',
        'listen, you don\'t like me, and i sure as hell don\'t like you. but if we don\'t do something, mr. mohawk\'s gonna activate this ring, and we\'re all gonna die',
        'you had your chance to be afraid before you joined my beloved corps. but, to guide you back to the true path, I brought this motivational device. our big green style cannot be defeated',
        'the chief is gonna jump in this tank, roll across the bridge, and blow up any inhuman son-of-a-bitch dumb enough to get between him and the prophet of regret. pull yourself together, \'cause you\'re going with him',
        'when I joined the corps, we didn\'t have any fancy-schmancy tanks. we had sticks. Two sticks, and a rock for the whole platoon—and we had to share the rock. buck up, boy, you are one very lucky marine',
        'usually, the good lord works in mysterious ways. but not today. This here is sixty six tons of straight-up, h e spewing dee vine intervention. if god is love, then you can call me cupid',
        'crazy fool. Why do you always jump. one of these days, you\'re gonna land on somethin\' as stubborn as you are. and I don\'t do bits and pieces',
        'we got enough to worry about without you two tryin\' to kill each other',
        'send me out... with a bang'
    ],
    'gravemind': [
        'Lies for the weak! Beacons for the deluded!',
        'this one is but flesh and faith, and is the more deluded',
        'This one is machine and nerve, and has its mind concluded.',
        'Arrogant creatures! Your deaths will be instantaneous, while we shall suffer the progress of infinitude!',
        'If you will not hear the truth, then I will show it to you. There is still time to stop the key from turning, but first, it must be found.',
        'Fate had us meet as foes, but this Ring will make us brothers.',
        'We exist together now, two corpses in one grave...',
        'Do not shoot, but listen! Let me lead you safely... to our foe. Only you can halt... what he has set in motion.',
        'Do not be afraid. I am peace; I am salvation.',
        'I am a timeless chorus. Join your voice with mine, and sing victory everlasting.',
        'Now the gate has been unlatched, headstones pushed aside; corpses shift and offer room, a fate you must abide!',
        'Time... has taught me patience! But basking in new freedom, I will know all that I possess!',
        'Do I take life or give it? Who is victim, and who is foe?',
        'Resignation is my virtue; like water I ebb, and flow. Defeat is simply the addition of time... to a sentence I never deserved... but you imposed.',
        'Do I take life or give it? Who is victim, and who is foe?',
        'I...? I... am a monument... to all your sins.'
    ],
    '3 4 3 guilty spark': [
        'someone released the flood. my function is to prevent it from leaving this installation. but i require your assistance. come. this way',
        'This installation\'s research facilities are most impressive! Perhaps we\'ll have time to see them later.',
        'The installation was specifically built to study and contain the Flood. Their survival as a race was dependent upon it.',
        'A construct? In the Core? That is absolutely unacceptable!',
        'Why would you hesitate to do what you have already done?',
        'There is no choice. We must activate the ring.',
        'So be it. Save his head. Dispose of the rest.',
        'Weapons of last resort. Built by the Forerunners to eliminate potential Flood hosts, thereby rendering the Parasite harmless',
        'Uncertain. This storage device has suffered considerable trauma. It\'s matrices are highly unstable.',
        'Two to the eighteenth light years from the galactic center, to be precise.',
        'Calamity! If only we had more time!',
        'I have begun my simulations. No promises, but initial results indicate that this facility should be ready to fire in just a few more days!',
        'Ow! That hurt...my feelings. ...Oh, my God, I have feelings?! I\'m a real boy!',
        'Maybe you should try playing on Easy before you search for the Cartographer',
        'Do you think bullets grow on trees?'
    ]
}